/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author Korisnik
 */
public class MainForma extends javax.swing.JFrame {

    /**
     * Creates new form MainForma
     */
    public MainForma() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContests = new javax.swing.JPanel();
        lblCompetitionsText = new javax.swing.JLabel();
        lblCompetitionsPhoto = new javax.swing.JLabel();
        panelContests1 = new javax.swing.JPanel();
        lblCompetitionsText1 = new javax.swing.JLabel();
        lblCompetitionsPhoto1 = new javax.swing.JLabel();
        panelContests2 = new javax.swing.JPanel();
        lblCompetitionsText2 = new javax.swing.JLabel();
        lblCompetitionsPhoto2 = new javax.swing.JLabel();
        panelContests3 = new javax.swing.JPanel();
        lblCompetitionsText3 = new javax.swing.JLabel();
        lblCompetitionsPhoto3 = new javax.swing.JLabel();
        panelContests4 = new javax.swing.JPanel();
        lblCompetitionsText4 = new javax.swing.JLabel();
        lblCompetitionsPhoto4 = new javax.swing.JLabel();
        panelLegalEntities = new javax.swing.JPanel();
        lblLegalEntityText = new javax.swing.JLabel();
        lblLegalEntityPhoto = new javax.swing.JLabel();
        panelFundings = new javax.swing.JPanel();
        lblLegalEntityText1 = new javax.swing.JLabel();
        lblLegalEntityPhoto1 = new javax.swing.JLabel();
        panelContests5 = new javax.swing.JPanel();
        lblCompetitionsText5 = new javax.swing.JLabel();
        lblCompetitionsPhoto5 = new javax.swing.JLabel();
        panelProjects = new javax.swing.JPanel();
        lblProjectsText = new javax.swing.JLabel();
        lblProjectsPhoto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblWelcomeMessage = new javax.swing.JLabel();
        lblHomeIcon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        panelContests.setBackground(new java.awt.Color(240, 240, 240));
        panelContests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelContestsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelContestsMouseExited(evt);
            }
        });

        lblCompetitionsText.setBackground(new java.awt.Color(45, 118, 232));
        lblCompetitionsText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCompetitionsText.setForeground(new java.awt.Color(45, 118, 232));
        lblCompetitionsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompetitionsText.setText("Konkursi");

        lblCompetitionsPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/competitions.png"))); // NOI18N
        lblCompetitionsPhoto.setText("jLabel1");
        lblCompetitionsPhoto.setMaximumSize(new java.awt.Dimension(48, 48));
        lblCompetitionsPhoto.setMinimumSize(new java.awt.Dimension(48, 48));
        lblCompetitionsPhoto.setPreferredSize(new java.awt.Dimension(48, 48));

        javax.swing.GroupLayout panelContestsLayout = new javax.swing.GroupLayout(panelContests);
        panelContests.setLayout(panelContestsLayout);
        panelContestsLayout.setHorizontalGroup(
            panelContestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestsLayout.createSequentialGroup()
                .addGroup(panelContestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContestsLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblCompetitionsPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContestsLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblCompetitionsText, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelContestsLayout.setVerticalGroup(
            panelContestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContestsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblCompetitionsPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblCompetitionsText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelContests1.setBackground(new java.awt.Color(240, 240, 240));
        panelContests1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelContests1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelContests1MouseExited(evt);
            }
        });

        lblCompetitionsText1.setBackground(new java.awt.Color(45, 118, 232));
        lblCompetitionsText1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCompetitionsText1.setForeground(new java.awt.Color(45, 118, 232));
        lblCompetitionsText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompetitionsText1.setText("Konkursi");

        lblCompetitionsPhoto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/competitions.png"))); // NOI18N
        lblCompetitionsPhoto1.setText("jLabel1");
        lblCompetitionsPhoto1.setMaximumSize(new java.awt.Dimension(48, 48));
        lblCompetitionsPhoto1.setMinimumSize(new java.awt.Dimension(48, 48));
        lblCompetitionsPhoto1.setPreferredSize(new java.awt.Dimension(48, 48));

        panelContests2.setBackground(new java.awt.Color(240, 240, 240));
        panelContests2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelContests2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelContests2MouseExited(evt);
            }
        });

        lblCompetitionsText2.setBackground(new java.awt.Color(45, 118, 232));
        lblCompetitionsText2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCompetitionsText2.setForeground(new java.awt.Color(45, 118, 232));
        lblCompetitionsText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompetitionsText2.setText("Konkursi");

        lblCompetitionsPhoto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/competitions.png"))); // NOI18N
        lblCompetitionsPhoto2.setText("jLabel1");
        lblCompetitionsPhoto2.setMaximumSize(new java.awt.Dimension(48, 48));
        lblCompetitionsPhoto2.setMinimumSize(new java.awt.Dimension(48, 48));
        lblCompetitionsPhoto2.setPreferredSize(new java.awt.Dimension(48, 48));

        panelContests3.setBackground(new java.awt.Color(240, 240, 240));
        panelContests3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelContests3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelContests3MouseExited(evt);
            }
        });

        lblCompetitionsText3.setBackground(new java.awt.Color(45, 118, 232));
        lblCompetitionsText3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCompetitionsText3.setForeground(new java.awt.Color(45, 118, 232));
        lblCompetitionsText3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompetitionsText3.setText("Konkursi");

        lblCompetitionsPhoto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/competitions.png"))); // NOI18N
        lblCompetitionsPhoto3.setText("jLabel1");
        lblCompetitionsPhoto3.setMaximumSize(new java.awt.Dimension(48, 48));
        lblCompetitionsPhoto3.setMinimumSize(new java.awt.Dimension(48, 48));
        lblCompetitionsPhoto3.setPreferredSize(new java.awt.Dimension(48, 48));

        panelContests4.setBackground(new java.awt.Color(240, 240, 240));
        panelContests4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelContests4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelContests4MouseExited(evt);
            }
        });

        lblCompetitionsText4.setBackground(new java.awt.Color(45, 118, 232));
        lblCompetitionsText4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCompetitionsText4.setForeground(new java.awt.Color(45, 118, 232));
        lblCompetitionsText4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompetitionsText4.setText("Konkursi");

        lblCompetitionsPhoto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/competitions.png"))); // NOI18N
        lblCompetitionsPhoto4.setText("jLabel1");
        lblCompetitionsPhoto4.setMaximumSize(new java.awt.Dimension(48, 48));
        lblCompetitionsPhoto4.setMinimumSize(new java.awt.Dimension(48, 48));
        lblCompetitionsPhoto4.setPreferredSize(new java.awt.Dimension(48, 48));

        javax.swing.GroupLayout panelContests4Layout = new javax.swing.GroupLayout(panelContests4);
        panelContests4.setLayout(panelContests4Layout);
        panelContests4Layout.setHorizontalGroup(
            panelContests4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContests4Layout.createSequentialGroup()
                .addGroup(panelContests4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContests4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblCompetitionsPhoto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContests4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblCompetitionsText4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelContests4Layout.setVerticalGroup(
            panelContests4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContests4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblCompetitionsPhoto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblCompetitionsText4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelContests3Layout = new javax.swing.GroupLayout(panelContests3);
        panelContests3.setLayout(panelContests3Layout);
        panelContests3Layout.setHorizontalGroup(
            panelContests3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContests3Layout.createSequentialGroup()
                .addGroup(panelContests3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContests3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblCompetitionsPhoto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContests3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblCompetitionsText3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(panelContests3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContests3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelContests4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelContests3Layout.setVerticalGroup(
            panelContests3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContests3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblCompetitionsPhoto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblCompetitionsText3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelContests3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContests3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelContests4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout panelContests2Layout = new javax.swing.GroupLayout(panelContests2);
        panelContests2.setLayout(panelContests2Layout);
        panelContests2Layout.setHorizontalGroup(
            panelContests2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContests2Layout.createSequentialGroup()
                .addGroup(panelContests2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContests2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblCompetitionsPhoto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContests2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblCompetitionsText2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(panelContests2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContests2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelContests3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelContests2Layout.setVerticalGroup(
            panelContests2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContests2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblCompetitionsPhoto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblCompetitionsText2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelContests2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContests2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelContests3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout panelContests1Layout = new javax.swing.GroupLayout(panelContests1);
        panelContests1.setLayout(panelContests1Layout);
        panelContests1Layout.setHorizontalGroup(
            panelContests1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContests1Layout.createSequentialGroup()
                .addGroup(panelContests1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContests1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblCompetitionsPhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContests1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblCompetitionsText1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(panelContests1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContests1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelContests2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelContests1Layout.setVerticalGroup(
            panelContests1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContests1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblCompetitionsPhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblCompetitionsText1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelContests1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContests1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelContests2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        panelLegalEntities.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelLegalEntitiesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelLegalEntitiesMouseExited(evt);
            }
        });

        lblLegalEntityText.setBackground(new java.awt.Color(45, 118, 232));
        lblLegalEntityText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLegalEntityText.setForeground(new java.awt.Color(45, 118, 232));
        lblLegalEntityText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLegalEntityText.setText("Pravna lica");

        lblLegalEntityPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/students.png"))); // NOI18N
        lblLegalEntityPhoto.setText("jLabel1");
        lblLegalEntityPhoto.setMaximumSize(new java.awt.Dimension(48, 48));
        lblLegalEntityPhoto.setMinimumSize(new java.awt.Dimension(48, 48));
        lblLegalEntityPhoto.setPreferredSize(new java.awt.Dimension(48, 48));

        javax.swing.GroupLayout panelLegalEntitiesLayout = new javax.swing.GroupLayout(panelLegalEntities);
        panelLegalEntities.setLayout(panelLegalEntitiesLayout);
        panelLegalEntitiesLayout.setHorizontalGroup(
            panelLegalEntitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLegalEntitiesLayout.createSequentialGroup()
                .addGroup(panelLegalEntitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLegalEntitiesLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblLegalEntityPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLegalEntitiesLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblLegalEntityText, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panelLegalEntitiesLayout.setVerticalGroup(
            panelLegalEntitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLegalEntitiesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblLegalEntityPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblLegalEntityText)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        panelFundings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelFundingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelFundingsMouseExited(evt);
            }
        });

        lblLegalEntityText1.setBackground(new java.awt.Color(45, 118, 232));
        lblLegalEntityText1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLegalEntityText1.setForeground(new java.awt.Color(45, 118, 232));
        lblLegalEntityText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLegalEntityText1.setText("Budžetiranje");

        lblLegalEntityPhoto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/competitions.png"))); // NOI18N
        lblLegalEntityPhoto1.setText("jLabel1");
        lblLegalEntityPhoto1.setMaximumSize(new java.awt.Dimension(48, 48));
        lblLegalEntityPhoto1.setMinimumSize(new java.awt.Dimension(48, 48));
        lblLegalEntityPhoto1.setPreferredSize(new java.awt.Dimension(48, 48));

        javax.swing.GroupLayout panelFundingsLayout = new javax.swing.GroupLayout(panelFundings);
        panelFundings.setLayout(panelFundingsLayout);
        panelFundingsLayout.setHorizontalGroup(
            panelFundingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFundingsLayout.createSequentialGroup()
                .addGroup(panelFundingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFundingsLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblLegalEntityPhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFundingsLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblLegalEntityText1)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panelFundingsLayout.setVerticalGroup(
            panelFundingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFundingsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblLegalEntityPhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblLegalEntityText1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelContests5.setBackground(new java.awt.Color(240, 240, 240));
        panelContests5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelContests5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelContests5MouseExited(evt);
            }
        });

        lblCompetitionsText5.setBackground(new java.awt.Color(45, 118, 232));
        lblCompetitionsText5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCompetitionsText5.setForeground(new java.awt.Color(45, 118, 232));
        lblCompetitionsText5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompetitionsText5.setText("Konkursi");

        lblCompetitionsPhoto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/competitions.png"))); // NOI18N
        lblCompetitionsPhoto5.setText("jLabel1");
        lblCompetitionsPhoto5.setMaximumSize(new java.awt.Dimension(48, 48));
        lblCompetitionsPhoto5.setMinimumSize(new java.awt.Dimension(48, 48));
        lblCompetitionsPhoto5.setPreferredSize(new java.awt.Dimension(48, 48));

        javax.swing.GroupLayout panelContests5Layout = new javax.swing.GroupLayout(panelContests5);
        panelContests5.setLayout(panelContests5Layout);
        panelContests5Layout.setHorizontalGroup(
            panelContests5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContests5Layout.createSequentialGroup()
                .addGroup(panelContests5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContests5Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblCompetitionsPhoto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContests5Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblCompetitionsText5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelContests5Layout.setVerticalGroup(
            panelContests5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContests5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblCompetitionsPhoto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblCompetitionsText5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelProjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelProjectsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelProjectsMouseExited(evt);
            }
        });

        lblProjectsText.setBackground(new java.awt.Color(45, 118, 232));
        lblProjectsText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblProjectsText.setForeground(new java.awt.Color(45, 118, 232));
        lblProjectsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProjectsText.setText("Projekti");

        lblProjectsPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/competitions.png"))); // NOI18N
        lblProjectsPhoto.setText("jLabel1");
        lblProjectsPhoto.setMaximumSize(new java.awt.Dimension(48, 48));
        lblProjectsPhoto.setMinimumSize(new java.awt.Dimension(48, 48));
        lblProjectsPhoto.setPreferredSize(new java.awt.Dimension(48, 48));

        javax.swing.GroupLayout panelProjectsLayout = new javax.swing.GroupLayout(panelProjects);
        panelProjects.setLayout(panelProjectsLayout);
        panelProjectsLayout.setHorizontalGroup(
            panelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProjectsLayout.createSequentialGroup()
                .addGroup(panelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProjectsLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblProjectsPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelProjectsLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblProjectsText, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelProjectsLayout.setVerticalGroup(
            panelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProjectsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblProjectsPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblProjectsText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main forma");

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));

        lblWelcomeMessage.setBackground(new java.awt.Color(45, 118, 232));
        lblWelcomeMessage.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        lblWelcomeMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWelcomeMessage.setText("Dobro došli");

        lblHomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblHomeIcon)
                .addGap(18, 18, 18)
                .addComponent(lblWelcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHomeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWelcomeMessage))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setForeground(new java.awt.Color(45, 118, 232));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/people.png"))); // NOI18N
        jButton1.setText("Radnici");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setForeground(new java.awt.Color(45, 118, 232));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tools.png"))); // NOI18N
        jButton2.setText("Predmer radova");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 255, 255));
        jButton3.setForeground(new java.awt.Color(45, 118, 232));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/company.png"))); // NOI18N
        jButton3.setText("Kompanije");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 255, 255));
        jButton4.setForeground(new java.awt.Color(45, 118, 232));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill.png"))); // NOI18N
        jButton4.setText("Narudžbenice");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 255, 255));
        jButton5.setForeground(new java.awt.Color(45, 118, 232));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paper.png"))); // NOI18N
        jButton5.setText("Zapisnik");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelContestsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelContestsMouseEntered
    }//GEN-LAST:event_panelContestsMouseEntered

    private void panelContestsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelContestsMouseExited
    }//GEN-LAST:event_panelContestsMouseExited

    private void panelContests1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelContests1MouseEntered
    }//GEN-LAST:event_panelContests1MouseEntered

    private void panelContests1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelContests1MouseExited
    }//GEN-LAST:event_panelContests1MouseExited

    private void panelContests2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelContests2MouseEntered
    }//GEN-LAST:event_panelContests2MouseEntered

    private void panelContests2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelContests2MouseExited
    }//GEN-LAST:event_panelContests2MouseExited

    private void panelContests3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelContests3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelContests3MouseEntered

    private void panelContests3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelContests3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelContests3MouseExited

    private void panelContests4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelContests4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelContests4MouseEntered

    private void panelContests4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelContests4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelContests4MouseExited

    private void panelLegalEntitiesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLegalEntitiesMouseEntered
    }//GEN-LAST:event_panelLegalEntitiesMouseEntered

    private void panelLegalEntitiesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLegalEntitiesMouseExited
    }//GEN-LAST:event_panelLegalEntitiesMouseExited

    private void panelFundingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFundingsMouseEntered
    }//GEN-LAST:event_panelFundingsMouseEntered

    private void panelFundingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFundingsMouseExited

    }//GEN-LAST:event_panelFundingsMouseExited

    private void panelContests5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelContests5MouseEntered
    }//GEN-LAST:event_panelContests5MouseEntered

    private void panelContests5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelContests5MouseExited
    }//GEN-LAST:event_panelContests5MouseExited

    private void panelProjectsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProjectsMouseEntered
    }//GEN-LAST:event_panelProjectsMouseEntered

    private void panelProjectsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProjectsMouseExited
    }//GEN-LAST:event_panelProjectsMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RadniciForma rf = new RadniciForma(this, true);
        rf.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PredmerRadovaForma prf = new PredmerRadovaForma(this, true);
        prf.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        KompanijeForma kf = new KompanijeForma(this, true);
        kf.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        NarudzbeniceForma nf = new NarudzbeniceForma(this, true);
        nf.setVisible(true);

}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ZapisniciForma zf = new ZapisniciForma(this, true);
        zf.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FlatLightLaf.setup();

                new MainForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCompetitionsPhoto;
    private javax.swing.JLabel lblCompetitionsPhoto1;
    private javax.swing.JLabel lblCompetitionsPhoto2;
    private javax.swing.JLabel lblCompetitionsPhoto3;
    private javax.swing.JLabel lblCompetitionsPhoto4;
    private javax.swing.JLabel lblCompetitionsPhoto5;
    private javax.swing.JLabel lblCompetitionsText;
    private javax.swing.JLabel lblCompetitionsText1;
    private javax.swing.JLabel lblCompetitionsText2;
    private javax.swing.JLabel lblCompetitionsText3;
    private javax.swing.JLabel lblCompetitionsText4;
    private javax.swing.JLabel lblCompetitionsText5;
    private javax.swing.JLabel lblHomeIcon;
    private javax.swing.JLabel lblLegalEntityPhoto;
    private javax.swing.JLabel lblLegalEntityPhoto1;
    private javax.swing.JLabel lblLegalEntityText;
    private javax.swing.JLabel lblLegalEntityText1;
    private javax.swing.JLabel lblProjectsPhoto;
    private javax.swing.JLabel lblProjectsText;
    private javax.swing.JLabel lblWelcomeMessage;
    private javax.swing.JPanel panelContests;
    private javax.swing.JPanel panelContests1;
    private javax.swing.JPanel panelContests2;
    private javax.swing.JPanel panelContests3;
    private javax.swing.JPanel panelContests4;
    private javax.swing.JPanel panelContests5;
    private javax.swing.JPanel panelFundings;
    private javax.swing.JPanel panelLegalEntities;
    private javax.swing.JPanel panelProjects;
    // End of variables declaration//GEN-END:variables
}
