/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domen.Kompanija;
import domen.Narudzbenica;
import domen.StavkaPodtipaRadova;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import logika.Kontroler;
import modelTabele.KompanijaModelTabele;
import modelTabele.NarudzbenicaModelTabele;
import modelTabele.StavkaPodtipaRadovaModelTabele;

/**
 *
 * @author Korisnik
 */
public class NarudzbeniceForma extends javax.swing.JDialog {

    /**
     * Creates new form NarudzbeniceFormaa
     */
    public NarudzbeniceForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        refresujFormu();
        designTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNarudzbenica = new javax.swing.JTable();
        btnAdd1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        panelSearch7 = new javax.swing.JPanel();
        lblStatus7 = new javax.swing.JLabel();
        btnFilter7 = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        btnReset7 = new javax.swing.JButton();
        cmbGod = new javax.swing.JComboBox<>();
        panelHeader = new javax.swing.JPanel();
        lblLegalEntityText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Narudžbenice");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblNarudzbenica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblNarudzbenica);

        btnAdd1.setText("Dodaj narudžbenicu");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        btnDelete1.setText("Obrisi narudžbenicu");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });

        btnUpdate1.setText("Ažuriraj narudžbenicu");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });

        panelSearch7.setBackground(new java.awt.Color(255, 255, 255));
        panelSearch7.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretraga"));

        lblStatus7.setText("Godina");

        btnFilter7.setText("Filtriraj");
        btnFilter7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilter7ActionPerformed(evt);
            }
        });

        btnReset7.setText("Resetuj");
        btnReset7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset7ActionPerformed(evt);
            }
        });

        cmbGod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "StareNarudzbenice", "Narudzbenice2021", "Narudzbenice2022", "Narudzbenice2023", "NoveNarudzbenice" }));

        javax.swing.GroupLayout panelSearch7Layout = new javax.swing.GroupLayout(panelSearch7);
        panelSearch7.setLayout(panelSearch7Layout);
        panelSearch7Layout.setHorizontalGroup(
            panelSearch7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearch7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSearch7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSearch7Layout.createSequentialGroup()
                        .addComponent(btnFilter7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                        .addComponent(btnReset7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearch7Layout.createSequentialGroup()
                        .addComponent(lblStatus7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbGod, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator9)
        );
        panelSearch7Layout.setVerticalGroup(
            panelSearch7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearch7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSearch7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus7)
                    .addComponent(cmbGod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSearch7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFilter7)
                    .addComponent(btnReset7))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnUpdate1)
                        .addGap(715, 715, 715)
                        .addComponent(btnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 714, Short.MAX_VALUE)
                        .addComponent(btnDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(715, 715, 715)
                .addComponent(panelSearch7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(panelSearch7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(btnAdd1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(btnDelete1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        panelHeader.setBackground(new java.awt.Color(45, 118, 232));

        lblLegalEntityText.setBackground(new java.awt.Color(45, 118, 232));
        lblLegalEntityText.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        lblLegalEntityText.setForeground(new java.awt.Color(255, 255, 255));
        lblLegalEntityText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLegalEntityText.setText("NARUDŽBENICE");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblLegalEntityText, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1569, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblLegalEntityText)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        final int selectedRow = tblNarudzbenica.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati Narudzbenicu koju zelite da izmenite!");
            return;
        }
        NarudzbenicaModelTabele nmt = (NarudzbenicaModelTabele) tblNarudzbenica.getModel();
        Narudzbenica n = nmt.returnObject(selectedRow);
        AzurirajNarudzbenicuForma dk = new AzurirajNarudzbenicuForma(this, n, true);
        dk.setVisible(true);
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        DodajNarudzbenicuForma dn = new DodajNarudzbenicuForma(this, true);
        dn.setVisible(true);
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        final int selectedRow = tblNarudzbenica.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Morate selektovati podatke Narudzbenice koju zelite da obrisete", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int odgovor = JOptionPane.showConfirmDialog(this, "Da li ste sigurni?", "Potvrda", JOptionPane.YES_NO_OPTION);
        NarudzbenicaModelTabele nmt = (NarudzbenicaModelTabele) tblNarudzbenica.getModel();
        Narudzbenica n = nmt.returnObject(selectedRow);
        if (odgovor == JOptionPane.YES_OPTION) {
            Kontroler.getInstanca().deleteNarudzbecnica(n.getId());
            nmt.remove(selectedRow);
            refresujFormu();

        }
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnFilter7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilter7ActionPerformed
        String uslov = (String) cmbGod.getSelectedItem();

        ArrayList<Narudzbenica> lista = Kontroler.getInstanca().getNarudzbenicePoGodini(uslov);
        tblNarudzbenica.setModel(new NarudzbenicaModelTabele(lista));
    }//GEN-LAST:event_btnFilter7ActionPerformed

    private void btnReset7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset7ActionPerformed
        refresujFormu();
    }//GEN-LAST:event_btnReset7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnFilter7;
    private javax.swing.JButton btnReset7;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JComboBox<String> cmbGod;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblLegalEntityText;
    private javax.swing.JLabel lblStatus7;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelSearch7;
    private javax.swing.JTable tblNarudzbenica;
    // End of variables declaration//GEN-END:variables

    public void refresujFormu() {
        ArrayList<Narudzbenica> lista = Kontroler.getInstanca().getAllNarudzbenica();
        tblNarudzbenica.setModel(new NarudzbenicaModelTabele(lista));

    }

    private void designTable() {
        tblNarudzbenica.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 15));
        tblNarudzbenica.getTableHeader().setOpaque(false);
        tblNarudzbenica.getTableHeader().setBackground(new Color(32, 136, 203));
        tblNarudzbenica.getTableHeader().setForeground(new Color(255, 255, 255));
        tblNarudzbenica.setRowHeight(25);
    }
}
